import type { RawDeal } from '@/types'

export const MOCK_FAIRPRICE_DEALS: RawDeal[] = [
  {
    name: 'Marigold UHT Milk - Full Cream 1L',
    store: 'fairprice',
    salePrice: 2.55,
    originalPrice: 3.2,
    savingAmount: 0.65,
    savingPct: 20.3,
    url: '/product/marigold-uht-milk',
    promoLabel: 'Save $0.65',
  },
  {
    name: "Farmhouse Fresh Eggs (10's)",
    store: 'fairprice',
    salePrice: 3.35,
    originalPrice: 3.95,
    savingAmount: 0.6,
    savingPct: 15.2,
    url: '/product/farmhouse-fresh-eggs',
    promoLabel: 'Save $0.60',
  },
  {
    name: 'Seara Frozen Chicken Breast - Boneless',
    store: 'fairprice',
    salePrice: 9.45,
    originalPrice: 11.7,
    savingAmount: 2.25,
    savingPct: 19.2,
    url: '/product/seara-frozen-chicken-breast',
    promoLabel: 'Save $2.25',
  },
  {
    name: 'Meiji Natural Yogurt 140g',
    store: 'fairprice',
    salePrice: 1.8,
    originalPrice: 2.1,
    savingAmount: 0.3,
    savingPct: 14.3,
    url: '/product/meiji-natural-yogurt',
    promoLabel: 'Save $0.30',
  },
  {
    name: 'Gardenia Original Classic Bread 400g',
    store: 'fairprice',
    salePrice: 2.4,
    originalPrice: 2.75,
    savingAmount: 0.35,
    savingPct: 12.7,
    url: '/product/gardenia-original-classic',
    promoLabel: 'Save $0.35',
  },
  {
    name: 'Anchor Butter Salted 250g',
    store: 'fairprice',
    salePrice: 5.5,
    originalPrice: 6.5,
    savingAmount: 1.0,
    savingPct: 15.4,
    url: '/product/anchor-butter-salted',
    promoLabel: 'Save $1.00',
  },
  {
    name: 'Fortune Fragrant Rice 5kg',
    store: 'fairprice',
    salePrice: 11.9,
    originalPrice: 13.9,
    savingAmount: 2.0,
    savingPct: 14.4,
    url: '/product/fortune-fragrant-rice',
    promoLabel: 'Save $2.00',
  },
  {
    name: 'Knife Cooking Oil 2L',
    store: 'fairprice',
    salePrice: 6.95,
    originalPrice: 8.5,
    savingAmount: 1.55,
    savingPct: 18.2,
    url: '/product/knife-cooking-oil',
    promoLabel: 'Save $1.55',
  },
  {
    name: 'Chef Red Onion - Large 500g',
    store: 'fairprice',
    salePrice: 1.5,
    originalPrice: null,
    savingAmount: null,
    savingPct: null,
    url: '/product/chef-red-onion',
    promoLabel: null,
  },
  {
    name: 'Barilla Pasta Spaghetti 500g',
    store: 'fairprice',
    salePrice: 3.2,
    originalPrice: 3.95,
    savingAmount: 0.75,
    savingPct: 19.0,
    url: '/product/barilla-pasta-spaghetti',
    promoLabel: 'Save $0.75',
  },
]

export const MOCK_COLDSTORAGE_DEALS: RawDeal[] = [
  {
    name: 'Greenfields Full Cream Fresh Milk 1L',
    store: 'coldstorage',
    salePrice: 3.45,
    originalPrice: 4.2,
    savingAmount: 0.75,
    savingPct: 17.9,
    url: '/product/greenfields-fresh-milk',
    promoLabel: '20% OFF',
  },
  {
    name: 'Happy Eggs Free Range 10pc',
    store: 'coldstorage',
    salePrice: 4.95,
    originalPrice: 5.95,
    savingAmount: 1.0,
    savingPct: 16.8,
    url: '/product/happy-eggs-free-range',
    promoLabel: 'Save $1.00',
  },
  {
    name: 'Tyson Fresh Chicken Breast Fillet 500g',
    store: 'coldstorage',
    salePrice: 7.9,
    originalPrice: 9.9,
    savingAmount: 2.0,
    savingPct: 20.2,
    url: '/product/tyson-chicken-breast',
    promoLabel: 'Save $2.00',
  },
  {
    name: 'Chobani Plain Greek Yogurt 170g',
    store: 'coldstorage',
    salePrice: 2.95,
    originalPrice: 3.6,
    savingAmount: 0.65,
    savingPct: 18.1,
    url: '/product/chobani-greek-yogurt',
    promoLabel: 'Save $0.65',
  },
  {
    name: 'Sunshine Enriched White Bread 500g',
    store: 'coldstorage',
    salePrice: 2.15,
    originalPrice: 2.65,
    savingAmount: 0.5,
    savingPct: 18.9,
    url: '/product/sunshine-enriched-white-bread',
    promoLabel: 'Save $0.50',
  },
  {
    name: 'Lurpak Slightly Salted Butter 200g',
    store: 'coldstorage',
    salePrice: 7.5,
    originalPrice: 9.0,
    savingAmount: 1.5,
    savingPct: 16.7,
    url: '/product/lurpak-butter',
    promoLabel: 'Save $1.50',
  },
  {
    name: 'Sunwhite Calrose Rice 5kg',
    store: 'coldstorage',
    salePrice: 14.5,
    originalPrice: null,
    savingAmount: null,
    savingPct: null,
    url: '/product/sunwhite-calrose-rice',
    promoLabel: null,
  },
  {
    name: 'Naturel Olive Oil Blend 1L',
    store: 'coldstorage',
    salePrice: 8.95,
    originalPrice: 10.9,
    savingAmount: 1.95,
    savingPct: 17.9,
    url: '/product/naturel-olive-oil-blend',
    promoLabel: 'Save $1.95',
  },
  {
    name: 'Divella Spaghetti No.9 500g',
    store: 'coldstorage',
    salePrice: 2.85,
    originalPrice: 3.5,
    savingAmount: 0.65,
    savingPct: 18.6,
    url: '/product/divella-spaghetti',
    promoLabel: 'Save $0.65',
  },
]
